### ISSUE TITLE
[FR] (Remove your Configuration_Secure.h)

### ISSUE THREAD

**Issue by carl1961** [dwhitlockii/Marlin_corexy_SKR-Pro1.1_bltouch#1]
Thanks for sharing your files, but you need to remove Configuration_Secure.h
this file has your private login stuff
also be best to also remove the .vscode folder, as that only points to file on your private computer

**Comment by dwhitlockii** [comment]
Thanks I was just testing the esp01 on the skr pro and thats why I forgot and left that file attached.   removed it
